fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    view:
        view_response_listener:
            enabled: true
            force: true
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
        - { path: ^/api/v1/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
        - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ text/html ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
