fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    use_listener: false
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: true
