api_v1:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /api/v1/

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc