main:
    type: xml
    prefix: /
    name_prefix: app_
    resource: '../src/Resources/routing/main_routes.xml'

api:
    type: rest
    prefix: /api/v1/
    name_prefix: api_v1_
    resource: '../src/Resources/routing/api_routes.xml'
