main:
    type: xml
    prefix: /
    name_prefix: main_
    resource: '../src/Resources/routing/main_routes.xml'

security:
    type: xml
    prefix: /
    name_prefix: security_
    resource: '../src/Resources/routing/security_routes.xml'

api:
    type: rest
    prefix: /api/v1/
    name_prefix: api_v1_
    resource: '../src/Resources/routing/api_routes.xml'
